/**
 * Which services EVERY order incurs.
 *
 * A product rule, not a per-row setting, and that distinction is the
 * whole reason this file exists rather than a database column.
 *
 * THE BUG THIS REPLACES, CAUGHT BEFORE IT SHIPPED. The rule briefly
 * lived as an `appliesToEveryOrder` flag on PricingService, set in
 * seed.ts. That works perfectly in development, where the catalogue IS
 * seed.ts. Production reads the catalogue from Supabase, and there is
 * no such column: every row would have mapped with the flag undefined,
 * so `quantityFollowsVolume` would have been false for pick & pack in
 * production and nowhere else.
 *
 * The consequence was not cosmetic. That flag is what prefills the
 * pick-and-pack quantity with the visitor's monthly order volume.
 * Without it the calculator falls back to a quantity of one, so a
 * seller shipping 1,000 orders a month is quoted for a single order,
 * which is the exact bug `quantityFollowsVolume` was introduced to fix
 * in the first place: a figure two orders of magnitude under the truth,
 * presented as their price.
 *
 * Keyed by slug because slug is the stable identifier across both
 * stores: ids are generated by Postgres in production and fixed
 * strings in the seed, so an id-keyed rule would work in exactly one
 * of the two environments, which is how this went wrong the first time.
 *
 * Adding to this set is a commercial decision. "Charged per order" is
 * not the test; "incurred by every single order" is. Rush handling,
 * gift wrapping and manual order entry are all charged per order and
 * none of them belong here, because prefilling a month with thousands
 * of them would quote a total nobody would recognise.
 */
export const APPLIES_TO_EVERY_ORDER: ReadonlySet<string> = new Set([
  // If an order shipped, it was picked and packed. That is the only
  // thing on the catalogue which is true of every order by definition.
  "pick-pack",
]);

export function appliesToEveryOrder(slug: string): boolean {
  return APPLIES_TO_EVERY_ORDER.has(slug);
}
