import type { PricingService } from "./types";

/**
 * Initial service catalogue.
 *
 * IMPORTANT: no real Dockcentra prices exist yet, so every priced service
 * is seeded with price = 0 and isActive = false. Nothing here appears in
 * the public calculator until an admin sets a real price and activates
 * the service. Do NOT invent commercial prices in this file.
 */
export const SEED_SERVICES: PricingService[] = [
  {
    id: "svc-receiving-carton",
    name: "Goods receiving",
    slug: "goods-receiving",
    description:
      "Receiving supplier deliveries, carton counting and discrepancy reporting.",
    category: "Receiving",
    unitLabel: "per carton",
    price: 0,
    currency: "EUR",
    pricingType: "PER_CARTON",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 10,
  },
  {
    id: "svc-storage-pallet-week",
    name: "Pallet storage",
    slug: "pallet-storage",
    description: "Local pallet storage in Ireland, billed weekly.",
    category: "Storage",
    unitLabel: "per pallet / week",
    price: 0,
    currency: "EUR",
    pricingType: "PER_WEEK",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 20,
  },
  {
    id: "svc-storage-bin-month",
    name: "Bin storage",
    slug: "bin-storage",
    description: "Small-item bin storage, billed monthly.",
    category: "Storage",
    unitLabel: "per bin / month",
    price: 0,
    currency: "EUR",
    pricingType: "PER_MONTH",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 30,
  },
  {
    id: "svc-pick-pack-order",
    name: "Pick & pack",
    slug: "pick-and-pack",
    description: "Picking, checking and packing an outgoing order.",
    category: "Pick & Pack",
    unitLabel: "per order",
    price: 0,
    currency: "EUR",
    pricingType: "PER_ORDER",
    minimumCharge: null,
    isActive: false,
    isFeatured: true,
    sortOrder: 40,
  },
  {
    id: "svc-extra-item",
    name: "Additional item in order",
    slug: "additional-item",
    description: "Each additional unit picked into the same order.",
    category: "Pick & Pack",
    unitLabel: "per item",
    price: 0,
    currency: "EUR",
    pricingType: "PER_ITEM",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 50,
  },
  {
    id: "svc-fnsku-labelling",
    name: "FNSKU / barcode labelling",
    slug: "fnsku-labelling",
    description: "Applying FNSKU or barcode labels for marketplace prep.",
    category: "Labelling",
    unitLabel: "per item",
    price: 0,
    currency: "EUR",
    pricingType: "PER_ITEM",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 60,
  },
  {
    id: "svc-polybagging",
    name: "Polybagging",
    slug: "polybagging",
    description: "Polybagging units including the bag and suffocation label.",
    category: "Prep",
    unitLabel: "per item",
    price: 0,
    currency: "EUR",
    pricingType: "PER_ITEM",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 70,
  },
  {
    id: "svc-bubble-wrap",
    name: "Bubble wrapping",
    slug: "bubble-wrapping",
    description: "Protective bubble wrapping for fragile units.",
    category: "Prep",
    unitLabel: "per item",
    price: 0,
    currency: "EUR",
    pricingType: "PER_ITEM",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 80,
  },
  {
    id: "svc-returns-processing",
    name: "Returns processing",
    slug: "returns-processing",
    description:
      "Receiving a return, inspection, photos if required and restock or separation.",
    category: "Returns",
    unitLabel: "per return",
    price: 0,
    currency: "EUR",
    pricingType: "PER_UNIT",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 90,
  },
  {
    id: "svc-packaging-materials",
    name: "Packaging materials",
    slug: "packaging-materials",
    description: "Boxes, mailers and void fill used per order.",
    category: "Packaging",
    unitLabel: "per order",
    price: 0,
    currency: "EUR",
    pricingType: "PER_ORDER",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 100,
  },
  {
    id: "svc-custom-kitting",
    name: "Custom kitting & bundling",
    slug: "custom-kitting",
    description:
      "Multi-item bundles, gift sets and kitting projects — quoted per project.",
    category: "Kitting",
    unitLabel: "custom quote",
    price: 0,
    currency: "EUR",
    pricingType: "CUSTOM_QUOTE",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 110,
  },
  {
    id: "svc-special-handling",
    name: "Special handling / oversized items",
    slug: "special-handling",
    description:
      "Oversized, heavy or unusual items and complex inspection work — quoted individually.",
    category: "Other",
    unitLabel: "custom quote",
    price: 0,
    currency: "EUR",
    pricingType: "CUSTOM_QUOTE",
    minimumCharge: null,
    isActive: false,
    isFeatured: false,
    sortOrder: 120,
  },
];
